### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by Augensternbaby** [isVy08/OTM#1]
Hello, I have some questions while learning your code and would like to ask you for answers. 

When I run the "python config.py" command, I get the error
 "Loading data ...
Loading data ...
Loading data ...
Generating real-world datasets ...
Generating and Saving neuro data ...
Generating and Saving neuro data ...
Traceback (most recent call last):
  File "E:Edge DownloadOTM2OTM-masterconfig.py", line 91, in <module>
get_data(config_id, 'REAL', sem_type)
  File "E:Edge DownloadOTM2OTM-masterconfig.py", line 58, in get_data
    dataset = RealDataset(n = config['num_obs'], d = config['num_vars'],
  File "E:Edge DownloadOTM2OTM-masterreal.py", line 26, in __init__
    self. B_bin = acc.load_graph_true_graph()
  File "E:Edge DownloadOTM2OTM-masternpdsCauAcc.py", line 36, in load_graph_true_graph
    with open('models/bnm.pickle', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'models/bnm.pickle'",

 but there is nothing in the models when you run the command, where is this "bnm.pickle"?

**Comment by isVy08** [comment]
Hi,
You can download the model bnm.pickle here: https://github.com/TURuibo/Neuropathic-Pain-Diagnosis-Simulator/tree/master/models

**Comment by Augensternbaby** [comment]
Thank you very much for your answer! The problem has been solved!
